### ISSUE TITLE
pyOptSparse Error when running pitzDaily case.

### ISSUE THREAD

**Issue by XueminLiu111** [DAFoam/tutorials#3]
Hi there, I'm trying to run the pitzDaily case using the latest DAForm docker image.
However, when I run 
`python runScript.py 2>&1 | tee logOpt.txt`
The following error appears 
`+------------------------------------------------------------------------------+
| pyOptSparse Error: There was an error importing the compiled snopt module    |
+------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "runScript.py", line 183, in <module>
    opt = OPT(args.opt, options=optOptions)
  File "/home/dafoamuser/dafoam/packages/miniconda3/lib/python3.6/site-packages/pyoptsparse/pyOpt_optimizer.py", line 941, in OPT
    return opt(*args, **kwargs)
  File "/home/dafoamuser/dafoam/packages/miniconda3/lib/python3.6/site-packages/pyoptsparse/pySNOPT/pySNOPT.py", line 227, in __init__
    raise Error("There was an error importing the compiled snopt module")
pyoptsparse.pyOpt_error.Error
I/O    : uncollated`

Could you help me solve this problem? Much appreciated!

**Comment by friedenhe** [comment]
SNOPT is commercial software and is not included in the docker image

**Comment by XueminLiu111** [comment]
Thank you! So do I need to re-build the docker image when getting the access of SNOPT?

**Comment by friedenhe** [comment]
Yes
