### ISSUE TITLE
Segmentation fault for CRM wing tutorial

### ISSUE THREAD

**Issue by AbhijithMoni** [DAFoam/tutorials#7]
When running the CRM wing tutorial the following error appears: 

`mpirun noticed that process rank 0 with PID 0 on node e5a390a53ebf exited on signal 11 (Segmentation fault).`

I have also tried without using `mpirun` by directly running it with the command `python runScript.py`, but it gives the same error. 

OS: Windows with Docker[dafoam/opt-packages:v3.0.0]

Any help is appreciated. 

Thanks.

**Comment by friedenhe** [comment]
You probably won't be able to run this case on your computer because of the memory limit. Try to run it on HPC.

**Comment by AbhijithMoni** [comment]
@friedenhe Thanks for your reply. I will try with HPC.
